global:
  scrape_interval: 15s # 15s will be enough, because block of time
  scrape_timeout: 15s
  evaluation_interval: 15s # Evaluate alerting
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 5s
scrape_configs:
  - job_name: 'coda-testnet'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['<NODE_IP_ADDRESS>:6060'] ## Replace IP address to your node
        labels:
          hostname: 'coda-daemon'
          
          
global:
  scrape_interval: 15s # 15s will be enough, because block of time
  scrape_timeout: 15s
  evaluation_interval: 15s # Evaluate alerting
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 5s
scrape_configs:
  - job_name: 'coda-testnet'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['<NODE_IP_ADDRESS>:6060'] ## Replace NODE_IP_ADDRESS to IP address of your server
        labels:
          hostname: 'coda-daemon'
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['<NODE_IP_ADDRESS>:9100']
